{txt = "copy", fn = },
{txt = "del", fn = },    --System.removeFile(path)
{txt = "erase", fn = },  --System.removeFile(path)
{txt = "move", fn = },
{txt = "rd", fn = },     --System.removeDirectory(path)
{txt = "rmdir", fn = },  --System.removeDirectory(path)
{txt = "md5", fn = },    --System.md5sum(String)
--{txt = "", fn = },

-- DEL    , {txt = "", fn = "", help = "Deletes one or more files", dhelp = {"Deletes one or more files.","","DEL names","ERASE names","","  names         Specifies a list of one or more files."}}