--*************************************************************************************************
-- Angelic Layer MMO (ALMMO) Lua Game
-- Coded by by alatnet
--*************************************************************************************************

red = Color.new(256, 0, 0)
green = Color.new(0, 256, 0)
blue = Color.new(0, 0, 256)
black = Color.new(0, 0, 0)
white = Color.new(256, 256, 256)
--cyan = Color.new(100, 256, 256)
yellow = Color.new(256,256,0)
lblue = Color.new(0,256,256)
purple = Color.new(256,0,256)
gray = Color.new(64, 64, 64)
orange = Color.new(256,128,64)
dgray = Color.new(180,180,180)